### ISSUE TITLE
When I tried to run evaluatie.py it reported the function incorrectly

### ISSUE THREAD

**Issue by baiyunfan123** [tgc1997/RMN#27]
(rmn) E:\video_caption\rmn\RMN-master>python evaluate.py --dataset=msvd --model=RMN  --result_dir=results/msvd_model --attention=gumbel  --use_loc --use_rel --use_func  --hidden_size=512 --att_size=512  --test_batch_size=2 --beam_size=
2  --eval_metric=CIDEr
335it [01:21,  4.13it/s]
init COCO-EVAL scorer
tokenization...
Traceback (most recent call last):
  File "evaluate.py", line 107, in <module>
    metrics = evaluate(opt, net, opt.test_range, opt.test_prediction_txt_path, reference)
  File "evaluate.py", line 75, in evaluate
    scores, sub_category_score = scorer.score(reference, prediction_json, prediction_json.keys())
  File "./caption-eval\cocoeval.py", line 64, in score
    print('tokenization...')
OSError: [WinError 1] 函数不正确。

**Comment by tgc1997** [comment]
Hi, we didn't test the code on Windows, so we haven't encountered this problem

**Comment by baiyunfan123** [comment]
Thank you for your reply!
